Repository sql-machine-learning/elasticdl, pull requests merged in 2019-12, with the labels that each got.

#1530 Implement a sparse embedding layer using TF embedding_lookup_sparse
  elasticdl/python/common/model_handler.py
  elasticdl/python/elasticdl/layers/embedding.py
  elasticdl/python/keras/layers/__init__.py
  elasticdl/python/keras/layers/sparse_embedding.py
  elasticdl/python/tests/model_handler_test.py
Labels: serving

#1540 Remove the outer loop for reporting embedding info.
  elasticdl/python/worker/worker.py
Labels: refactor

#1541 BUGFIX: generate_mock_embedding_vectors will fail if id >= (dimension of embedding)
  elasticdl/python/tests/feature_column_test.py
Labels: bug

#1546 BUGFIX: elasticdl.python.keras module is not found
  elasticdl/python/keras/__init__.py
Labels: bug
