Repository sql-machine-learning/elasticdl, pull requests merged in 2019-10, with the labels that each got.

#1278 Model evaluation implementation design
  docs/designs/evaluation_design.md
  docs/images/evaluate_sequence.svg
  docs/images/train_and_evaluate_flowchart.svg
  docs/images/train_and_evaluate_flowchart_proposal.svg
Labels: document

#1330 ElasticDL serving design
  docs/designs/serving_design.md
  docs/images/saved_model_task.png
Labels: serving

#1395 Rename initializer parameter to keep consistency with Keras
  elasticdl/python/elasticdl/layers/embedding.py
Labels: refactor
