Repository sql-machine-learning/elasticdl, pull requests merged in 2019-11, with the labels that each got.

#1400 Restore keras model and parameters to export.
  elasticdl/python/common/model_handler.py
  elasticdl/python/elasticdl/layers/embedding.py
  elasticdl/python/tests/model_handler_test.py
Labels: serving

#1399 Pass save model task parameter from client CLI to the worker execution
  elasticdl/proto/elasticdl.proto
  elasticdl/python/common/constants.py
  elasticdl/python/master/master.py
  elasticdl/python/master/servicer.py
  elasticdl/python/master/task_dispatcher.py
  elasticdl/python/tests/task_dispatcher_test.py
  elasticdl/python/worker/worker.py
Labels: serving

#1420 Add design doc for allreduce-based distributed training
  docs/designs/allreduce.md
Labels: design doc

#1483 Process the dataset by dataset_fn to build model.
  elasticdl/python/worker/worker.py
Labels: bug

#1488 ElasticDL Training checkpoints Design.
  docs/designs/checkpoint_design.md
Labels: design doc

#1497 Fix loss log.
  elasticdl/python/worker/worker.py
Labels: bug

#1477 Data transform design doc
  docs/designs/data_transform.md
  docs/images/data_transform_pipeline.png
  docs/images/transform_steps.png
Labels: design doc
