Repository sql-machine-learning/elasticdl, pull requests merged in 2020-01, with the labels that each got.

#1622 Check whether the file and directory exists before deleting
  elasticdl/python/common/save_utils.py
Labels: bug

#1672 Refactor the structure of data transform design.
  docs/designs/data_transform.md
  docs/images/transform_training_inference.png
Labels: data transform, design doc

#1671 Add a wide and deep model with feature group embeddings.
  elasticdl/docker/Dockerfile.dev
  elasticdl/python/tests/example_test.py
  elasticdl/python/tests/test_utils.py
  model_zoo/census_wide_deep_model/feature_config.py
  model_zoo/census_wide_deep_model/feature_info_util.py
  model_zoo/census_wide_deep_model/keras_process_layer.py
  model_zoo/census_wide_deep_model/wide_deep_functional_api.py
Labels: data transform
